### ISSUE TITLE
Sage doctest failing when built with clang because of missing symbol in libpynac.

### ISSUE THREAD

**Issue by kiwifb** [pynac/pynac#239]
The following doctest is failing when pynac/sage are built entirely with clang on OS X
```
sage -t --long --warn-long 62.3 src/sage/libs/pynac/pynac.pxd
**********************************************************************
File "src/sage/libs/pynac/pynac.pxd", line 10, in sage.libs.pynac.pynac
Failed example:
    cython(  # long time
    '''
    #clang c++
    #clib pynac
    #cargs --std=c++11
    cimport sage.libs.pynac.pynac
    ''')
Exception raised:
    Traceback (most recent call last):
      File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 498, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 861, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.pynac.pynac[0]>", line 7, in <module>
        ''')
      File "sage/misc/lazy_import.pyx", line 389, in sage.misc.lazy_import.LazyImport.__call__ (/Users/fbissey/build/sage-clang/src/build/cythonized/sage/misc/lazy_import.c:4007)
        return self._get_object()(*args, **kwds)
      File "sage/misc/cython_c.pyx", line 65, in sage.misc.cython_c.cython_compile (/Users/fbissey/build/sage-clang/src/build/cythonized/sage/misc/cython_c.c:1187)
        cython_import_all(tmpfile, get_globals(),
      File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/misc/cython.py", line 710, in cython_import_all
        create_local_c_file=create_local_c_file)
      File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/misc/cython.py", line 689, in cython_import
        return builtins.__import__(name)
    ImportError: dlopen(/Users/fbissey/.sage/temp/Mirage.local/52652/spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx_0.so, 2): Symbol not found: __ZTVN5GiNaC9containerISt6vectorEE
      Referenced from: /Users/fbissey/.sage/temp/Mirage.local/52652/spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx_0.so
      Expected in: flat namespace
     in /Users/fbissey/.sage/temp/Mirage.local/52652/spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx_0.so
**********************************************************************
```
The symbol is indeed not in libpynac.dylib as build with clang on OS X, but it is present when built with gcc on linux.

**Comment by rwst** [comment]
Demangled: `_vtable for GiNaC::container<std::vector>`. Again, a template problem.

**Comment by kiwifb** [comment]
I could have provided that. I guess it saves you a bit of time to figure it out.

**Comment by rwst** [comment]
No problem. There is demangler.com

**Comment by kiwifb** [comment]
`c++filt` comes with your compiler for that. Granted from OS X to linux you may want to remove one leading underscore, but there is an option for that `-_`.

**Comment by isuruf** [comment]
@kiwifb, can you try adding a virtual destructor for `GiNaC::container`?

**Comment by kiwifb** [comment]
I am a C++ ignoramus, you would have to tell me where and how. You might as well write it for me.

**Comment by isuruf** [comment]
What pynac version are you using?

**Comment by kiwifb** [comment]
0.7.5

**Comment by isuruf** [comment]
```diff
diff --git a/ginac/container.h b/ginac/container.h
index 3dd53ba..8af2ab0 100644
--- a/ginac/container.h
+++ b/ginac/container.h
@@ -146,6 +146,9 @@ protected:
        static const char* get_open_delim() { return "("; }
        static const char* get_close_delim() { return ")"; }
 
+       // destructor
+public:
+      virtual ~container() {};
        // constructors
 public:
        container(STLT const & s, bool discardable = false) : inherited(get_tinfo())
```

**Comment by kiwifb** [comment]
Still missing.

**Comment by kiwifb** [comment]
I should have said. When examining the library with `nm` there are plenty of `container` objects around. What there isn't, is `_ZTVN5GiNaC9containerISt6vector*` objects so the vector bit is actually essential.

**Comment by kiwifb** [comment]
I think it may be due to inlining
```
/** Specialization of container::remove_first() for std::vector. */
template<> inline container<std::vector> & container<std::vector>::remove_first()
{
	ensure_if_modifiable();
	this->seq.erase(this->seq.begin());
	return *this;
}
```
I'll have to dig but I think I saw something about it the other day, while looking at the problem for `fplll`.

**Comment by isuruf** [comment]
You might be right. I don't think that's valid C++.

**Comment by kiwifb** [comment]
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/CppRuntimeEnv/Articles/SymbolVisibility.html

We might want to play with visibility. That's something I can test and enable from `configure.ac` if it works out.

**Comment by kiwifb** [comment]
Hum, that's worse when compiling with `-visibility=hidden`
```
Mirage:sage-clang fbissey$ ./sage -t --long --warn-long 62.3 src/sage/libs/pynac/pynac.pxd
Traceback (most recent call last):
  File "/Users/fbissey/build/sage-clang/src/bin/sage-runtests", line 81, in <module>
    from sage.doctest.control import DocTestController
  File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/doctest/control.py", line 33, in <module>
    from .sources import FileDocTestSource, DictAsObject
  File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/doctest/sources.py", line 33, in <module>
    from .parsing import SageDocTestParser
  File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/doctest/parsing.py", line 52, in <module>
    from sage.all import RealIntervalField
  File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/all.py", line 107, in <module>
    from sage.symbolic.all   import *
  File "/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/symbolic/all.py", line 3, in <module>
    from sage.libs.pynac.pynac import I
ImportError: dlopen(/Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/libs/pynac/pynac.so, 2): Symbol not found: __ZN5GiNaC12library_initD1Ev
  Referenced from: /Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/libs/pynac/pynac.so
  Expected in: flat namespace
 in /Users/fbissey/build/sage-clang/local/lib/python2.7/site-packages/sage/libs/pynac/pynac.so
Mirage:sage-clang fbissey$ c++filt __ZN5GiNaC12library_initD1Ev
GiNaC::library_init::~library_init()
```

**Comment by kiwifb** [comment]
I also tried to remove the "inline" keyword but that resulted in multiple definitions for some symbols and the library refused to link.

**Comment by isuruf** [comment]
Can you post all the symbols in `libpynac.dylib`?

**Comment by isuruf** [comment]
I think this is not a Pynac issue, but of sage mixing the C++ runtimes.

**Comment by kiwifb** [comment]
How so? Everything is built with clang/clang++. You are sure you want the list of symbols?

**Comment by isuruf** [comment]
I checked in travis and I see something like, `__ZTVN5GiNaC9containerINSt3__16vectorEEE`. Do you also have that in `libpynac.dylib`?

`__ZTVN5GiNaC9containerINSt3__16vectorEEE` demangled is `_vtable for GiNaC::container<std::__1::vector>`.

`__ZTVN5GiNaC9containerISt6vectorEE` demangled is `_vtable for GiNaC::container<std::vector>`

Note `std::__1::vector` which is the `libc++` symbol and `std::vector` which I'm pretty sure is from `libstdc++`

**Comment by kiwifb** [comment]
Yes
```
Mirage:sage-clang fbissey$ nm local/lib/libpynac.dylib | grep __ZTVN5GiNaC9containerINSt3
00000000001ec840 d __ZTVN5GiNaC9containerINSt3__14listEEE
00000000001ef588 D __ZTVN5GiNaC9containerINSt3__16vectorEE7visitorE
00000000001ef370 D __ZTVN5GiNaC9containerINSt3__16vectorEEE
```
Those are all the symbols of that kind. Now I understand better what you mean
```
Mirage:sage-clang fbissey$ otool -L local/lib/libpynac.dylib 
local/lib/libpynac.dylib:
	/Users/fbissey/build/sage-clang/local/lib/libpynac.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/Users/fbissey/build/sage-clang/local/lib/libfactory-4.0.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.5.0)
	/Users/fbissey/build/sage-clang/local/lib/libntl.31.dylib (compatibility version 32.0.0, current version 32.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libomalloc-0.9.6.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libsingular_resources-4.0.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libflint-13.5.2.dylib (compatibility version 13.5.0, current version 13.5.2)
	/Users/fbissey/build/sage-clang/local/lib/libgmp.16.dylib (compatibility version 23.0.0, current version 23.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
and no mention of `libstdc++`, would need to compare with a gcc build on OS X to be sure but on gcc+linux we indeed have `libstdc++`
```
fbissey@moonloop ~ $ ldd -r /usr/lib64/libpynac.so
	linux-vdso.so.1 (0x00007ffdd7387000)
	libpython2.7.so.1.0 => /usr/lib64/libpython2.7.so.1.0 (0x00007f60aab96000)
	libfactory-4.1.0.so => /usr/lib64/libfactory-4.1.0.so (0x00007f60aa7c3000)
	libflint.so.13 => /usr/lib64/libflint.so.13 (0x00007f60aa24f000)
	libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f60a9fd7000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6 (0x00007f60a9bdd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f60a98e0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f60a9547000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1 (0x00007f60a9330000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f60a9113000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f60a8f0f000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f60a8d0c000)
	libsingular_resources-4.0.3.so => /usr/lib64/libsingular_resources-4.0.3.so (0x00007f60a8b05000)
	libomalloc-0.9.6.so => /usr/lib64/libomalloc-0.9.6.so (0x00007f60a88fa000)
	libntl.so.31 => /usr/lib64/libntl.so.31 (0x00007f60a84d6000)
	libmpfr.so.4 => /usr/lib/libmpfr.so.4 (0x00007f60a8272000)
	/lib64/ld-linux-x86-64.so.2 (0x0000561466266000)
	libgf2x.so.1 => /usr/lib64/libgf2x.so.1 (0x00007f60a8064000)
```

**Comment by isuruf** [comment]
Can you also give the library dependencies of `/Users/fbissey/.sage/temp/Mirage.local/52652/spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx/_Users_fbissey__sage_temp_Mirage_local_52652_tmp_xBtZja_spyx_0.so` ?

**Comment by kiwifb** [comment]
Good call
```
Mirage:sage-clang fbissey$ CC=clang CXX=clang++ ./sage -t --long src/sage/libs/pynac/pynac.pxd
too few successful tests, not using stored timings
Running doctests with ID 2017-03-27-21-04-47-8631b9d2.
Git branch: develop
Using --optional=mpir,python2,sage
Doctesting 1 file.
sage -t --long src/sage/libs/pynac/pynac.pxd
    [1 test, 3.69 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 3.7 seconds
    cpu time: 0.5 seconds
    cumulative wall time: 3.7 seconds
```
so the failure happened because the test was using g++ instead of clang. So the issue is not with pynac but with how we tell sage about the toolchain to use. And for info what you asked for is more proof of it
```
Mirage:~ fbissey$ otool -L /Users/fbissey/.sage/temp/Mirage.local/59630/spyx/_Users_fbissey__sage_temp_Mirage_local_59630_tmp_2f0f_f_spyx/_Users_fbissey__sage_temp_Mirage_local_59630_tmp_2f0f_f_spyx_0.so
/Users/fbissey/.sage/temp/Mirage.local/59630/spyx/_Users_fbissey__sage_temp_Mirage_local_59630_tmp_2f0f_f_spyx/_Users_fbissey__sage_temp_Mirage_local_59630_tmp_2f0f_f_spyx_0.so:
	/Users/fbissey/build/sage-clang/local/lib/libpynac.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.5.0)
	/Users/fbissey/build/sage-clang/local/lib/libgmp.16.dylib (compatibility version 23.0.0, current version 23.2.0)
	/Users/fbissey/build/sage-clang/local/lib/libgmpxx.8.dylib (compatibility version 13.0.0, current version 13.2.0)
	/Users/fbissey/build/sage-clang/local/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.21.0)
	/Users/fbissey/build/sage-clang/local/lib/libpari-gmp.dylib (compatibility version 2.9.0, current version 2.9.1)
	/Users/fbissey/build/sage-clang/local/lib/libec.3.dylib (compatibility version 4.0.0, current version 4.4.0)
	/Users/fbissey/build/sage-clang/local/lib/libgsl.19.dylib (compatibility version 20.0.0, current version 20.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libopenblas_haswell-r0.2.19.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libntl.31.dylib (compatibility version 32.0.0, current version 32.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/Users/fbissey/build/sage-clang/local/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Thanks Isuru. This can be closed.
