### ISSUE TITLE
print order does not know about infinity

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#32]
See http://trac.sagemath.org/ticket/17321
```
sage: cmp(SR(oo), sqrt(2))

Breakpoint 5, GiNaC::print_order::compare (this=0x7fffffffbbe0, lh=..., rh=...)
    at order.cpp:281
281             throw (std::runtime_error("comparing typeid's"));

(gdb) bt
#0  GiNaC::print_order::compare (this=0x7fffffffbbe0, lh=..., rh=...) at order.cpp:281
#1  0x00007fffcc8bf85b in GiNaC::print_order::compare (this=0x7fffffffbbe0, lhex=..., 
    rhex=...) at order.cpp:119
#2  0x00007fffcc344824 in __pyx_f_4sage_8symbolic_10expression_10Expression__cmp_c_impl
    (__pyx_v_left=<optimized out>, __pyx_v_right=<optimized out>)
    at build/cythonized/sage/symbolic/expression.cpp:18872
#3  0x00007fffe6caa98f in __pyx_f_4sage_9structure_7element_7Element__cmp (

(gdb) p typeid_lh
$1 = (const GiNaC::tinfo_t) 0x7fffcc8c0eab <GiNaC::infinity::tinfo_static>
(gdb) p typeid_rh
$2 = (const GiNaC::tinfo_t) 0x7fffcc8c4528 <GiNaC::power::tinfo_static>
```
See also #22.

**Comment by rwst** [comment]
In current Sage:
```
sage: cmp(SR(oo), sqrt(2))
1
```
